export let config = {
    "token": "Njk1MzgyNzIxMTIzNTgxOTYz.XpRqhA.ytqByXPTOjhBlfv-f6ur45U04XM",
    "developers":["572512230701006851","404681937249370123"],
    "prefix": "?",
    "nodes":[
        {
         "host":"localhost",
         "port":2333,
         "password":"youshallnotpass"
        } 
    ],
    // commands array is now completely useless,so it's gonna be list of all commands for backup
    "commands": [
        "help",
        "testCommand",
        "kick",
        "ban",
        "purge",
        "serverinfo",
        "join",
        "leave",
        "queue",
        "skip",
        "pause",
        "resume",
        "ascii",
        "poll",
        "play",
        "eval",
        "loop",
        "unloop",
        "shuffle",
        "nowplaying",
        //"apec",
        "image",
        "newapex",
        "userinfo",
        "softban",
        "mute",
        "meme",
        "unmute",
        "addrole",
        "removeroll",
        "covid",
        "randomf",
        "equalizer",
        "astronomy",
        "anime",
        "shutdown",
        "weather",
        "jump",
        "wcupdate",
        "welcometest",
        "trial",
        "radio",
        "volume",
        "ping",
        
    ]}